8. Reverse a vector (first element becomes last) (★☆☆)
9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
11. Create a 3x3 identity matrix (★☆☆)
12. Create a 3x3x3 array with random values (★☆☆)
13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
15. Create a 2d array with 1 on the border and 0 inside (★☆

https://numpy.org/doc/1.22/reference/index.html#reference

https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb

In [1]:
import numpy as np


# 8 - Reverse a vector (first element becomes last) 

In [2]:
v1 = np.arange(1,9)
print("original vector:", v1)

original vector: [1 2 3 4 5 6 7 8]


In [4]:
rev_v1 = v1[::-1]
print("reverse vector:", rev_v1)

reverse vector: [8 7 6 5 4 3 2 1]


In [ ]:
# 9 - Create a 3x3 matrix with values ranging from 0 to 8

In [5]:
mat1 = np.arange(0,9).reshape(3,3)
print("the matrix is : ", mat1)

the matrix is :  [[0 1 2]
 [3 4 5]
 [6 7 8]]


# 10 - Find indices of non-zero elements from [1,2,0,0,4,0]

In [6]:
arr_test = np.array([1,2,0,0,4,0])
print("the test array is", arr_test)

non_zero_elements = np.nonzero(arr_test)
print( "the non-zero elements is", non_zero_elements)

the test array is [1 2 0 0 4 0]
the non-zero elements is (array([0, 1, 4]),)


# 11 - Create a 3x3 identity matrix 

In [7]:
from numpy.core.numeric import identity
ident_mat = np.identity(4)
print("the identity matrix is \n", ident_mat)

the identity matrix is 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 12 - Create a 3x3x3 array with random values

In [8]:
rand_arr = np.random.random((3,3,3))

print ("the randon array is \n", rand_arr)

the randon array is 
 [[[0.1268967  0.77840121 0.95104774]
  [0.22540823 0.18359625 0.16918368]
  [0.87565212 0.41666728 0.16789073]]

 [[0.46931257 0.016642   0.52685633]
  [0.41582742 0.69745521 0.91987304]
  [0.99546611 0.76172341 0.53222193]]

 [[0.75925531 0.30094552 0.70779651]
  [0.7273576  0.30417351 0.95754357]
  [0.99046312 0.77291101 0.00442329]]]


# 13 - Create a 10x10 array with random values and find the minimum and maximum values

In [9]:
r_arr = np.random.random((10,10))
r_arr_min, r_arr_max = r_arr.min(), r_arr.max()

print("the randon array is \n", r_arr)
print("\nthe min value is ", r_arr_min,"\n the max value is ", r_arr_max)

the randon array is 
 [[0.65327965 0.96227898 0.51484231 0.42067361 0.60129767 0.82901223
  0.75065994 0.68716553 0.87269427 0.94623752]
 [0.87419254 0.55445996 0.60337121 0.60768165 0.98986162 0.58512606
  0.53165173 0.07340191 0.29104185 0.88479841]
 [0.75827525 0.22141536 0.11787662 0.20714215 0.23731834 0.53937534
  0.69578878 0.8630827  0.03113218 0.04848542]
 [0.20158589 0.99011217 0.64831037 0.92185517 0.13599232 0.59775031
  0.32710794 0.17805017 0.5133845  0.37526537]
 [0.75528589 0.07094733 0.33103463 0.08825902 0.84335599 0.11202107
  0.8346856  0.47473076 0.10423714 0.02805963]
 [0.08289409 0.78534748 0.0916534  0.36699268 0.35795193 0.05395844
  0.99048559 0.83898167 0.78163489 0.70011207]
 [0.16312019 0.59626734 0.89750978 0.92079598 0.89937192 0.55663545
  0.9002038  0.47879075 0.62936358 0.98388568]
 [0.37256541 0.97157289 0.3695664  0.31314437 0.23583429 0.20807701
  0.14174406 0.76984734 0.54418551 0.89953135]
 [0.96747119 0.5599287  0.34587712 0.75486133 0.00636759 0

# 15 - Create a 2d array with 1 on the border and 0 inside

In [ ]:
arr = np.ones((8,8))
print(" the 2d array is \n", arr)

arr[1:-1,1:-1] = 0
print(" the new 2d array is \n", arr)


 the 2d array is 
 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
 the new 2d array is 
 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


# 18 - Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 